apiVersion: v1
kind: Namespace
metadata:
  name: iot-edge

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zim-iot-data-api-config
  namespace: iot-edge
data:
  PROFILE: "prod"
  DATABASE_HOST: "postgresql-cp.iot-db"
  DATABASE_NAME: "cp-db"
  DATABASE_PORT: "5432"

---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyI0NGNlNzg5Yi1rcjEtcmVnaXN0cnkuY29udGFpbmVyLm5obmNsb3VkLmNvbS9jb250YWluZXItcGxhdGZvcm0tcmVnaXN0cnkiOnsidXNlcm5hbWUiOiJYQ0ExT2owRnFBOE9NaGFsT1VoSyIsInBhc3N3b3JkIjoiekdneG83WGxwazVvalk3diIsImF1dGgiOiJXRU5CTVU5cU1FWnhRVGhQVFdoaGJFOVZhRXM2ZWtkbmVHODNXR3h3YXpWdmFsazNkZz09In19fQ==
kind: Secret
metadata:
  name: ncr
  namespace: iot-edge
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
  name: zim-iot-data-api-secret
  namespace: iot-edge
type: Opaque
data:
  DATABASE_USER: YWRtaW4=  # echo -n 'admin' | base64
  DATABASE_PASSWORD: bWFzdGVy  # echo -n 'master' | base64

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zim-iot-data-api-deployment
  namespace: iot-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zim-iot-data-api-app
  template:
    metadata:
      labels:
        app: zim-iot-data-api-app
    spec:
      containers:
        - name: zim-iot-data-api-container
          image: 44ce789b-kr1-registry.container.nhncloud.com/container-platform-registry/zim-kafka-consumer:latest
          ports:
            - containerPort: 8080
          env:
            - name: PROFILE
              valueFrom:
                configMapKeyRef:
                  name: zim-iot-data-api-config
                  key: PROFILE
          envFrom:
            - configMapRef:
                name: zim-iot-data-api-config
            - secretRef:
                name: zim-iot-data-api-secret
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
      imagePullSecrets:
        - name: ncr

---
apiVersion: v1
kind: Service
metadata:
  name: zim-iot-data-api-service
  namespace: iot-edge
spec:
  selector:
    app: zim-iot-data-api-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
